### ISSUE TITLE
DOC: documentation not searchable?

### ISSUE THREAD

**Issue by jablka** [apache/cordova-docs#1338] opened 2023-10-03 14:31 UTC
this is probably a bug: the official documentation website is not searchable?

Try typing anything in the search bar [https://cordova.apache.org/docs/en/latest/](https://cordova.apache.org/docs/en/latest/)

I get no search results, as if the button does not work.

**Comment by breautek** [comment] 2023-10-21 11:34
Duplicate of https://github.com/apache/cordova-docs/issues/1294#issuecomment-1750561330

**Closed by breautek** 2023-10-21 11:34 UTC
Labels: bug, help wanted, Hacktoberfest
