### ISSUE TITLE
cordova-android 7.0.0 doesn't support API level 27, but the documentation suggests it does

### ISSUE THREAD

**Issue by ariofrio** [apache/cordova-docs#879] opened 2018-08-22 19:43 UTC
**Issue Type**
[X] Bug
[ ] Feature Request

**Priority**
[ ] Minor 
[X] Major 
[ ] Critical 
[ ] Blocker 

**Environment**
* OS: Android
* Browser: N/A

**Description**

When reading the documentation [on the Android platform support in Cordova](https://github.com/apache/cordova-docs/blob/master/www/docs/en/dev/guide/platforms/android/index.md), it says that 7.X.X supports API level up to 27.

> cordova-android Version | Supported Android API-Levels | Equivalent Android Version
> ------------------------|------------------------------|-----------------------------
> 7.X.X                   | 19 - 27                      | 4.4 - 8.1
> 6.X.X                   | 16 - 26                      | 4.1 - 8.0.0
> 5.X.X                   | 14 - 23                      | 4.0 - 6.0.1
> 4.1.X                   | 14 - 22                      | 4.0 - 5.1
> 4.0.X                   | 10 - 22                      | 2.3.3 - 5.1
> 3.7.X                   | 10 - 21                      | 2.3.3 - 5.0.2

However, when I tried to run the emulator ("cordova emulate android"), it didn't work, failing with "Cannot read property 'semver' of null" in platforms/android/cordova/lib/emulator.js.

The problem is that "cordova platform add android" (for cordova 8.0.0, the latest version) installs cordova-android 7.0.0, which doesn't include support for API level 27.

According to the documentation, [p"every release of cordova CLI pins a version for each platform"](https://cordova.apache.org/docs/en/latest/reference/cordova-cli/index.html#cordova-platform-command), which means that the upper limit in the above table is often misleading.

**Comment by brodybits** [comment] 2018-08-22 19:57
Marked as a bug, for now at least. Will need some further testing on our part.

**Comment by ariofrio** [comment] 2018-08-22 20:58
Thanks! Since the documentation recommends using the latest API Level supported by the version of cordova-android, this seems like something that every new project currently runs into.

**Comment by janpio** [comment] 2018-08-22 21:42
Which API levels do work with `cordova-android` 7.0.0 in your experience or testing @ariofrio?

**Comment by ariofrio** [comment] 2018-08-22 22:48
- `cordova-android` 7.0.0 [depends on `android-versions 1.2.1`](https://github.com/apache/cordova-android/blob/4b06eecf3eb4aba4add5731e2f36d69199ba3136/package.json#L32)
  - Since `android-versions` is a bundled dependency, the latest applicable version of it when `cordova-android` 7.0.0 was published is the one that is always used, unless a new version of `cordova-android` is built and published
- `android-versions` [does not include Oreo MR1 (API Level 27) until version 1.3.0](https://github.com/dvoiss/android-versions/commit/f9772c197a75709df703a2cf339b4427032b08d3)

**Comment by janpio** [comment] 2018-08-23 08:00
Makes sense. Could you please practically confirm this? Otherwise some Cordova developer will have to do so.

I guess the table was meant "the latest release of `cordova-android` 7.x.x supports". 
But it might make sense to add the individual releases to the table, right? 
Problem: Who volunteers to find out all those data points?

**Comment by breautek** [comment] 2021-01-14 21:38
Closing this as the issue is obsolete and won't be corrected.

`cordova-android` does not use bundled dependencies anymore so moving forward I don't think we will see this issue again.

**Closed by breautek** 2021-01-14 21:38 UTC
Labels: bug
