### ISSUE TITLE
Fix headline anchors that are currently broken

### ISSUE THREAD

**Issue by janpio** [apache/cordova-docs#881] opened 2018-08-27 08:48 UTC
For example https://cordova.apache.org/docs/en/latest/reference/cordova-cli/ has many headlines "Syntax" that all have the same anchor `#syntax` and link to https://cordova.apache.org/docs/en/latest/reference/cordova-cli/#syntax - which is not really what is wanted.

**Comment by janpio** [comment] 2018-08-27 08:48
Possibly a solution: https://about.gitlab.com/2016/07/19/markdown-kramdown-tips-and-tricks/#custom-ids (if we actually use kramdown - I am not sure)

**Comment by breautek** [comment] 2022-02-08 19:52
Closing as the issue is no longer reproducible.

**Closed by breautek** 2022-02-08 19:52 UTC
Labels: bug
