### ISSUE TITLE
Documentation body text is hard to read

### ISSUE THREAD

**Issue by ttencate** [apache/cordova-docs#927] opened 2019-01-22 08:47 UTC
**Issue Type**
[x] Bug
[ ] Feature Request

**Priority**
[x] Minor 
[ ] Major 
[ ] Critical 
[ ] Blocker 

**Environment**
* OS: Arch Linux
* Browser: Chromium

**Description**
As much as I love the Raleway typeface, it was designed as a display typeface for headlines and such, and is much too thin to be used as body text. Combine this with the pale base colour of `#333`, and the result is needlessly hard to read. I find myself going into my browser inspector and turning off these CSS rules, and my eyes go "ahhhhhh". And that's for someone with decent eyesight.

A straightforward fix would be to use one of the [heavier Raleway weights](https://fonts.google.com/specimen/Raleway). Alternatively, switch to a typeface more suited for body text; from Google Fonts's suggestions, Open Sans, Lato and Montserrat are all suitable.

**Comment by janpio** [comment] 2019-01-22 09:45
You are not wrong.

Do you want to create a PR with a suggestion? Include 2 screenshots with the before and after for easy evaluation. Thanks!

**Comment by ttencate** [comment] 2019-01-22 10:33
Odd. I'm using Chromium. It's a lot better in Firefox. The `font-weight` is 400 in both cases.

**Comment by GedasGa** [comment] 2019-03-18 08:00
I wasn't able to reproduce this issue with **Chrome**, **Firefox** or **Safari** on **macOS**. For me, the website looks exactly the same as for @janpio. Text in the `documentation body` does not seem to be low-contrast. 

You may wanna check if this has been reported as a bug in **Chromium** [issues list](https://bugs.chromium.org/p/chromium/issues/list). They could have some unexpected rendering issue on their end.

However, I've ran **Lighthouse** audit and noticed that some of `h2`, `a` and `span` elements do not have a sufficient contrast ratio and might difficult or impossible for many users to read.

**Comment by ttencate** [comment] 2019-03-18 08:06
I have since encountered this on several other sites. It's definitely a Chrome issue, although I couldn't find any actual bug report. [This StackOverflow thread](https://webmasters.stackexchange.com/questions/74672/rendering-of-raleway-google-web-fonts-in-google-chrome-browser) seems to be about a different issue, which was fixed years ago.

I wonder if Chrome isn't actually doing the right thing here and all the other browsers are wrong. Raleway is, after all, very thin, so it makes sense to make lines lighter than `#000` if they are less than a pixel wide.

Regardless of where the blame lies, this can probably be fixed in Cordova docs with a few well-placed lines of CSS.

**Comment by dblotsky** [comment] 2019-03-18 08:12
> The contributor that built that site is most probably not around any more.

I’m around, and I watch. :) @janpio Not sure I understand the problem though. Is it just to make the font bigger?

**Comment by ttencate** [comment] 2019-03-18 11:07
@dblotsky No, it's to use a different font for body (paragraph) text. Raleway is fine for headings and such, but it was never designed for large text blocks.

**Comment by dblotsky** [comment] 2019-03-20 03:56
@ttencate which font do you propose instead of Raleway for the body of text in the docs?

**Comment by dblotsky** [comment] 2019-03-20 03:59
@ttencate @GedasGa @janpio for reference, this is what my page looks like in Safari.

<img width="1440" alt="cordova-site" src="https://user-images.githubusercontent.com/405489/54658274-dff71e00-4a89-11e9-88d4-4bdaeff3d286.png">

**Comment by ttencate** [comment] 2019-03-27 15:43
@dblotsky The really thin Raleway seems to be a Chrome + Linux issue. Suggestions for alternative fonts are in the original issue report.

**Comment by dblotsky** [comment] 2019-04-07 23:30
@ttencate would you like to propose a PR with a higher font weight [here](https://github.com/apache/cordova-docs/blob/master/www/static/css-src/_docs.scss#L18), and post screenshots of the result on Chrome + Linux, and on other platforms?

**Comment by ttencate** [comment] 2019-04-08 07:34
I was going to do that, but instead I stumbled upon the root cause of the issue. My system has a version of Raleway installed that already contains "weight 400", but with much lighter contents. Perhaps this is the "original" Raleway, rather than the 2012 multi-weight remake. And for weight 400, this takes precedence over the Raleway hosted by Google Fonts. This leads to the strange situation that both 300 and 500 look heavier than 400 on my system (and both are quite readable).

To fix this, we'd need to force the browser to use the web font. [Here's how we can do this](https://stackoverflow.com/questions/40019408/force-chrome-to-use-external-font-in-css): give the font in the `@font-face` rule a custom name, so it doesn't match anything that might be installed on the user's system. To do that in Cordova Docs, we'd need to copy the CSS that Google serves up (carefully, because they do browser detection).

Because that CSS points to WOFF files etc. whose URLs might change (unlikely but possible), we might also want host the fonts ourselves; [here's how to download them](https://stackoverflow.com/a/27696481/14637).

I can make the PR, but I need some input: do we...

* ... host the fonts ourselves, incurring extra traffic, as well as browser cache misses because many folks will have Google's fonts cached, or...
* ... hotlink the font files from Google, with the slight risk that the URLs stop working at some point?

**Comment by ttencate** [comment] 2019-04-12 07:28
Confirmed: I uninstalled the Arch Linux AUR package `otf-raleway` (because it also made other sites unreadable) and it has resolved this issue for me.

The solution outlined above could still be applied, but if I was the only one complaining then it's not worth the trouble.

**Comment by dblotsky** [comment] 2019-04-15 05:43
Thanks for finding the root cause of the issue, @ttencate!

**Comment by breautek** [comment] 2022-02-08 19:58
No one has complained since 2019, and I don't encounter the same issue on Ubuntu 20, so I'll be closing this issue.

**Closed by breautek** 2022-02-08 19:58 UTC
