### ISSUE TITLE
Cordova Plugins Search not loading 

### ISSUE THREAD

**Issue by alijamal14** [apache/cordova-docs#1217] opened 2021-11-19 07:37 UTC
# Bug Report

## Problem
Cordova Plugins search not working 
![image](https://user-images.githubusercontent.com/2056312/142583184-f93de095-c871-459b-a5fc-3e68c7b7505c.png)

### What is expected to happen?
Cordova Plugins Search should show some plugin list

### What does actually happen?
It is showing Loading and nothing loads also if I search nothing is returned.

### Command or Code

Visit https://cordova.apache.org/plugins/

## Checklist

- [x] I searched for existing GitHub issues
- [x] I included all the necessary information above

**Comment by timbru31** [comment] 2021-11-19 09:01
Duplicate of #1128

**Closed by timbru31** 2021-11-19 09:01 UTC
